repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ --autofix, --no-sort-keys ]
        exclude: >
          (?x)^(
              .*\.ipynb
          )$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
